version: "3"
services:
  app:
    image: chat-server
    ports:
      - "3005:3005"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo
    platform: linux/arm64
    ports:
      - "27017:27017"
